local tab = require("fret.tab")

describe("tab data model", function()
  it("creates a song with one section containing one empty measure", function()
    local song = tab.new({ time_sig = { num = 4, den = 4 }, subdivision = 4 })
    assert.equals(4, song.time_sig.num)
    assert.equals(4, song.time_sig.den)
    assert.equals(1, #song.sections)
    assert.equals(1, #song.sections[1].measures)
    assert.equals(16, tab.slots_per_measure(song)) -- 4 beats * 4 subdivisions
  end)

  it("sets and gets a note", function()
    local song = tab.new()
    tab.set_note(song, 1, 1, 1, 1, 5) -- sec 1, measure 1, slot 1, string e, fret 5
    assert.equals(5, tab.get_note(song, 1, 1, 1, 1))
    assert.is_nil(tab.get_note(song, 1, 1, 1, 2))
  end)

  it("clears a note with nil", function()
    local song = tab.new()
    tab.set_note(song, 1, 1, 1, 1, 7)
    tab.set_note(song, 1, 1, 1, 1, nil)
    assert.is_nil(tab.get_note(song, 1, 1, 1, 1))
  end)

  it("adds a measure to a section", function()
    local song = tab.new()
    tab.add_measure(song, 1)
    assert.equals(2, #song.sections[1].measures)
  end)

  it("does not remove the last measure in a section", function()
    local song = tab.new()
    tab.remove_measure(song, 1, 1)
    assert.equals(1, #song.sections[1].measures)
  end)

  it("removes a measure when more than one exists", function()
    local song = tab.new()
    tab.add_measure(song, 1)
    tab.remove_measure(song, 1, 1)
    assert.equals(1, #song.sections[1].measures)
  end)

  it("adds a section", function()
    local song = tab.new()
    tab.add_section(song)
    assert.equals(2, #song.sections)
  end)

  it("does not remove the last section", function()
    local song = tab.new()
    tab.remove_section(song, 1)
    assert.equals(1, #song.sections)
  end)

  it("removes a section when more than one exists", function()
    local song = tab.new()
    tab.add_section(song)
    tab.remove_section(song, 1)
    assert.equals(1, #song.sections)
  end)

  it("sets and clears a section name", function()
    local song = tab.new()
    tab.set_section_name(song, 1, "Verse")
    assert.equals("Verse", song.sections[1].name)
    tab.set_section_name(song, 1, "")
    assert.is_nil(song.sections[1].name)
  end)

  it("toggles repeat markers", function()
    local song = tab.new()
    assert.is_false(song.sections[1].repeat_start)
    tab.toggle_repeat_start(song, 1)
    assert.is_true(song.sections[1].repeat_start)
    tab.toggle_repeat_end(song, 1)
    assert.is_true(song.sections[1].repeat_end)
  end)
end)

describe("render", function()
  local render = require("fret.render")
  local config = require("fret.config")
  config.setup({})

  it("produces header + ruler + 6 string lines for one section (no title)", function()
    local song = tab.new({ time_sig = { num = 4, den = 4 }, subdivision = 1 })
    local lines = render.render(song)
    assert.equals(8, #lines) -- 1 section-header + 1 ruler + 6 strings
  end)

  it("prepends title/subtitle/order and a blank line", function()
    local song = tab.new({ title = "My Song", subtitle = "Guitar Tab", order = "A B A" })
    local lines = render.render(song)
    -- 3 header lines + 1 blank + 8 section lines = 12
    assert.equals(12, #lines)
    assert.equals("My Song",    lines[1])
    assert.equals("Guitar Tab", lines[2])
    assert.equals("Order: A B A", lines[3])
    assert.equals("",           lines[4])
  end)

  it("ruler contains the time signature", function()
    local song = tab.new({ time_sig = { num = 3, den = 4 }, subdivision = 1 })
    local lines = render.render(song)
    assert.truthy(lines[2]:match("^3/4")) -- ruler is line 2 (after section header)
  end)

  it("reflects a placed note in the rendered output", function()
    local song = tab.new({ time_sig = { num = 4, den = 4 }, subdivision = 1 })
    tab.set_note(song, 1, 1, 1, 1, 12) -- sec 1, meas 1, slot 1, string e, fret 12
    local lines = render.render(song)
    assert.truthy(lines[3]:match("12")) -- string e is line 3 (section-header + ruler + e)
  end)

  it("two sections produce correct line count", function()
    local song = tab.new({ time_sig = { num = 4, den = 4 }, subdivision = 1 })
    tab.add_section(song)
    local lines = render.render(song)
    -- sec1: 8 lines + 1 blank + sec2: 8 lines = 17
    assert.equals(17, #lines)
  end)

  it("section header shows name and repeat markers", function()
    local song = tab.new()
    tab.set_section_name(song, 1, "Verse")
    tab.toggle_repeat_start(song, 1)
    tab.toggle_repeat_end(song, 1)
    local lines = render.render(song)
    local hdr = lines[1]
    assert.truthy(hdr:match("%|:"))
    assert.truthy(hdr:match("%[Verse%]"))
    assert.truthy(hdr:match(":%|"))
  end)
end)
