local tab = require("fret.tab")

-- ── data model ────────────────────────────────────────────────────────────────

describe("tab data model", function()
  it("creates a song with one section containing one empty measure", function()
    local song = tab.new({ time_sig = { num = 4, den = 4 }, subdivision = 4 })
    assert.equals(4, song.time_sig.num)
    assert.equals(4, song.time_sig.den)
    assert.equals(1, #song.sections)
    assert.equals(1, #song.sections[1].measures)
    assert.equals(16, tab.slots_per_measure(song))
  end)

  it("defaults to 4/4 time, subdivision 4, no metadata", function()
    local song = tab.new()
    assert.equals(4, song.time_sig.num)
    assert.equals(4, song.time_sig.den)
    assert.equals(4, song.subdivision)
    assert.is_nil(song.title)
    assert.is_nil(song.subtitle)
    assert.is_nil(song.tuning)
    assert.is_nil(song.order)
  end)

  it("stores title, subtitle, tuning and order", function()
    local song = tab.new({ title = "My Song", subtitle = "By Me", tuning = "Drop D", order = "A B A" })
    assert.equals("My Song", song.title)
    assert.equals("By Me",   song.subtitle)
    assert.equals("Drop D",  song.tuning)
    assert.equals("A B A",   song.order)
  end)

  it("treats empty string metadata as nil", function()
    local song = tab.new({ title = "", subtitle = "", tuning = "", order = "" })
    assert.is_nil(song.title)
    assert.is_nil(song.subtitle)
    assert.is_nil(song.tuning)
    assert.is_nil(song.order)
  end)

  it("sets and gets a note", function()
    local song = tab.new()
    tab.set_note(song, 1, 1, 1, 1, 5)
    assert.equals(5, tab.get_note(song, 1, 1, 1, 1))
    assert.is_nil(tab.get_note(song, 1, 1, 1, 2))
  end)

  it("accepts fret 0 (open string)", function()
    local song = tab.new()
    tab.set_note(song, 1, 1, 1, 1, 0)
    assert.equals(0, tab.get_note(song, 1, 1, 1, 1))
  end)

  it("accepts fret 24 (upper boundary)", function()
    local song = tab.new()
    tab.set_note(song, 1, 1, 1, 1, 24)
    assert.equals(24, tab.get_note(song, 1, 1, 1, 1))
  end)

  it("rejects fret 25 (above maximum)", function()
    local song = tab.new()
    tab.set_note(song, 1, 1, 1, 1, 25)
    assert.is_nil(tab.get_note(song, 1, 1, 1, 1))
  end)

  it("rejects negative frets", function()
    local song = tab.new()
    tab.set_note(song, 1, 1, 1, 1, -1)
    assert.is_nil(tab.get_note(song, 1, 1, 1, 1))
  end)

  it("clears a note with nil", function()
    local song = tab.new()
    tab.set_note(song, 1, 1, 1, 1, 7)
    tab.set_note(song, 1, 1, 1, 1, nil)
    assert.is_nil(tab.get_note(song, 1, 1, 1, 1))
  end)

  it("returns nil for out-of-range section, measure, or slot", function()
    local song = tab.new()
    assert.is_nil(tab.get_note(song, 99, 1, 1, 1))
    assert.is_nil(tab.get_note(song, 1, 99, 1, 1))
  end)

  it("adds a measure to a section", function()
    local song = tab.new()
    tab.add_measure(song, 1)
    assert.equals(2, #song.sections[1].measures)
  end)

  it("does not remove the last measure in a section", function()
    local song = tab.new()
    tab.remove_measure(song, 1, 1)
    assert.equals(1, #song.sections[1].measures)
  end)

  it("removes a measure when more than one exists", function()
    local song = tab.new()
    tab.add_measure(song, 1)
    tab.remove_measure(song, 1, 1)
    assert.equals(1, #song.sections[1].measures)
  end)

  it("adds a section", function()
    local song = tab.new()
    tab.add_section(song)
    assert.equals(2, #song.sections)
  end)

  it("does not remove the last section", function()
    local song = tab.new()
    tab.remove_section(song, 1)
    assert.equals(1, #song.sections)
  end)

  it("removes a section when more than one exists", function()
    local song = tab.new()
    tab.add_section(song)
    tab.remove_section(song, 1)
    assert.equals(1, #song.sections)
  end)

  it("sets and clears a section name", function()
    local song = tab.new()
    tab.set_section_name(song, 1, "Verse")
    assert.equals("Verse", song.sections[1].name)
    tab.set_section_name(song, 1, "")
    assert.is_nil(song.sections[1].name)
  end)

  it("toggles repeat markers", function()
    local song = tab.new()
    assert.is_false(song.sections[1].repeat_start)
    tab.toggle_repeat_start(song, 1)
    assert.is_true(song.sections[1].repeat_start)
    tab.toggle_repeat_end(song, 1)
    assert.is_true(song.sections[1].repeat_end)
  end)

  it("set_time_sig resets all measures and clears notes", function()
    local song = tab.new({ time_sig = { num = 4, den = 4 }, subdivision = 1 })
    tab.set_note(song, 1, 1, 1, 1, 5)
    tab.set_time_sig(song, 3, 4)
    assert.is_nil(tab.get_note(song, 1, 1, 1, 1))
    assert.equals(3, tab.slots_per_measure(song))
  end)

  it("set_time_sig preserves measure count", function()
    local song = tab.new({ time_sig = { num = 4, den = 4 }, subdivision = 1 })
    tab.add_measure(song, 1)
    tab.add_measure(song, 1)
    tab.set_time_sig(song, 3, 4)
    assert.equals(3, #song.sections[1].measures)
  end)

  it("set_subdivision resets all measures and clears notes", function()
    local song = tab.new({ time_sig = { num = 4, den = 4 }, subdivision = 1 })
    tab.set_note(song, 1, 1, 1, 1, 5)
    tab.set_subdivision(song, 2)
    assert.is_nil(tab.get_note(song, 1, 1, 1, 1))
    assert.equals(8, tab.slots_per_measure(song))
  end)
end)

-- ── render ────────────────────────────────────────────────────────────────────

describe("render", function()
  local render = require("fret.render")
  local config = require("fret.config")
  config.setup({})

  it("produces header + bar numbers + ruler + 6 string lines for one section (no title, quarter grid)", function()
    local song = tab.new({ time_sig = { num = 4, den = 4 }, subdivision = 1 })
    local lines = render.render(song)
    assert.equals(9, #lines)
  end)

  it("adds duration row when any slot has an explicit duration", function()
    local song = tab.new({ time_sig = { num = 4, den = 4 }, subdivision = 1 })
    tab.set_note(song, 1, 1, 1, 1, 5)
    tab.set_duration(song, 1, 1, 1, 4)
    local lines = render.render(song)
    assert.equals(10, #lines)
  end)

  it("prepends title, subtitle and order with a blank separator", function()
    local song = tab.new({ title = "My Song", subtitle = "Guitar Tab", order = "A B A" })
    local lines = render.render(song)
    -- 3 header lines + 1 blank + 9 section lines = 13
    assert.equals(13, #lines)
    assert.equals("My Song",      lines[1])
    assert.equals("Guitar Tab",   lines[2])
    assert.equals("Order: A B A", lines[3])
    assert.equals("",             lines[4])
  end)

  it("includes tuning in header", function()
    local song = tab.new({ title = "T", tuning = "Drop D" })
    local lines = render.render(song)
    assert.truthy(vim.tbl_contains(lines, "Tuning: Drop D"))
  end)

  it("ruler contains the time signature", function()
    local song = tab.new({ time_sig = { num = 3, den = 4 }, subdivision = 1 })
    local lines = render.render(song)
    assert.truthy(lines[3]:match("^3/4"))
  end)

  it("bar numbers line appears above the ruler", function()
    local song = tab.new({ time_sig = { num = 4, den = 4 }, subdivision = 1 })
    tab.add_measure(song, 1)
    local lines = render.render(song)
    -- lines[2] is the bar numbers line; it should contain "1" and "2"
    assert.truthy(lines[2]:find("1", 1, true))
    assert.truthy(lines[2]:find("2", 1, true))
    -- and must not look like the ruler (no time-sig prefix)
    assert.falsy(lines[2]:match("^%d+/%d+"))
  end)

  it("reflects a placed note on the e string in the rendered output", function()
    local song = tab.new({ time_sig = { num = 4, den = 4 }, subdivision = 1 })
    tab.set_note(song, 1, 1, 1, 1, 12)
    local lines = render.render(song)
    assert.truthy(lines[4]:match("12"))
  end)

  it("note on B string (index 2) appears on the B row and not on e", function()
    local song = tab.new({ time_sig = { num = 4, den = 4 }, subdivision = 1 })
    tab.set_note(song, 1, 1, 1, 2, 7)
    local lines = render.render(song)
    assert.truthy(lines[4]:match("^e"))
    assert.falsy(lines[4]:match("[0-9]"))
    assert.truthy(lines[5]:match("^B"))
    assert.truthy(lines[5]:match("7"))
  end)

  it("notes on all six strings appear on their respective rows", function()
    local song = tab.new({ time_sig = { num = 4, den = 4 }, subdivision = 1 })
    tab.set_note(song, 1, 1, 1, 1, 5)
    tab.set_note(song, 1, 1, 1, 2, 4)
    tab.set_note(song, 1, 1, 1, 3, 3)
    tab.set_note(song, 1, 1, 1, 4, 2)
    tab.set_note(song, 1, 1, 1, 5, 1)
    tab.set_note(song, 1, 1, 1, 6, 0)
    local lines = render.render(song)
    assert.truthy(lines[4]:match("5"))
    assert.truthy(lines[5]:match("4"))
    assert.truthy(lines[6]:match("3"))
    assert.truthy(lines[7]:match("2"))
    assert.truthy(lines[8]:match("1"))
    assert.truthy(lines[9]:match("0"))
  end)

  it("all empty slots render as dashes with no digits", function()
    local song = tab.new({ time_sig = { num = 4, den = 4 }, subdivision = 1 })
    local lines = render.render(song)
    for i = 4, 9 do
      assert.falsy(lines[i]:match("[0-9]"), "string row " .. i .. " should have no digits")
      assert.truthy(lines[i]:match("-"),    "string row " .. i .. " should have dashes")
    end
  end)

  it("subdivision produces dot labels for non-beat slots", function()
    local song = tab.new({ time_sig = { num = 2, den = 4 }, subdivision = 2 })
    local lines = render.render(song)
    assert.truthy(lines[3]:match("1"))
    assert.truthy(lines[3]:match("2"))
    assert.truthy(lines[3]:match("%."))
  end)

  it("two measures produce three bar separators in the ruler", function()
    local song = tab.new({ time_sig = { num = 4, den = 4 }, subdivision = 1 })
    tab.add_measure(song, 1)
    local lines = render.render(song)
    assert.equals(9, #lines)
    local _, bars = lines[3]:gsub("%|", "")
    assert.equals(3, bars)
  end)

  it("double-digit fret renders without dashes after the digits", function()
    local song = tab.new({ time_sig = { num = 4, den = 4 }, subdivision = 1 })
    tab.set_note(song, 1, 1, 1, 1, 12)
    local lines = render.render(song)
    assert.truthy(lines[4]:find("12", 1, true))
    assert.falsy(lines[4]:find("12-", 1, true))
  end)

  it("single-digit fret in a widened slot is space-padded, not dash-padded", function()
    local song = tab.new({ time_sig = { num = 4, den = 4 }, subdivision = 1 })
    tab.set_note(song, 1, 1, 1, 1, 12)  -- e: forces slot width = 2
    tab.set_note(song, 1, 1, 1, 2, 5)   -- B: fret 5 in a 2-wide slot
    local lines = render.render(song)
    assert.truthy(lines[5]:find(" 5", 1, true))
    assert.falsy(lines[5]:find("5-", 1, true))
  end)

  it("two sections produce correct line count with blank separator", function()
    local song = tab.new({ time_sig = { num = 4, den = 4 }, subdivision = 1 })
    tab.add_section(song)
    local lines = render.render(song)
    -- sec1: 9 + 1 blank + sec2: 9 = 19
    assert.equals(19, #lines)
  end)

  it("section header shows name and repeat markers", function()
    local song = tab.new()
    tab.set_section_name(song, 1, "Verse")
    tab.toggle_repeat_start(song, 1)
    tab.toggle_repeat_end(song, 1)
    local lines = render.render(song)
    assert.truthy(lines[1]:match("%|:"))
    assert.truthy(lines[1]:match("%[Verse%]"))
    assert.truthy(lines[1]:match(":%|"))
  end)

  it("unnamed section with no repeats renders as ---", function()
    local song = tab.new()
    local lines = render.render(song)
    assert.equals("---", lines[1])
  end)
end)

-- ── JSON round-trip ───────────────────────────────────────────────────────────

describe("JSON round-trip", function()
  local function normalize(song)
    for _, sec in ipairs(song.sections or {}) do
      for _, m in ipairs(sec.measures or {}) do
        for _, slot in ipairs(m.slots or {}) do
          for k, v in pairs(slot) do
            if v == vim.NIL then slot[k] = nil end
          end
        end
      end
    end
    return song
  end

  local function rt(song) return normalize(vim.json.decode(vim.json.encode(song))) end

  it("notes on all six strings survive encode/decode", function()
    local song = tab.new({ time_sig = { num = 4, den = 4 }, subdivision = 1 })
    tab.set_note(song, 1, 1, 1, 1, 5)
    tab.set_note(song, 1, 1, 1, 2, 4)
    tab.set_note(song, 1, 1, 1, 3, 3)
    tab.set_note(song, 1, 1, 1, 4, 2)
    tab.set_note(song, 1, 1, 1, 5, 1)
    tab.set_note(song, 1, 1, 1, 6, 0)
    local loaded = rt(song)
    assert.equals(5, tab.get_note(loaded, 1, 1, 1, 1))
    assert.equals(4, tab.get_note(loaded, 1, 1, 1, 2))
    assert.equals(3, tab.get_note(loaded, 1, 1, 1, 3))
    assert.equals(2, tab.get_note(loaded, 1, 1, 1, 4))
    assert.equals(1, tab.get_note(loaded, 1, 1, 1, 5))
    assert.equals(0, tab.get_note(loaded, 1, 1, 1, 6))
  end)

  it("e string is nil when only non-e strings have notes (no vim.NIL bleed)", function()
    local song = tab.new({ time_sig = { num = 4, den = 4 }, subdivision = 1 })
    tab.set_note(song, 1, 1, 1, 2, 4)
    tab.set_note(song, 1, 1, 1, 3, 3)
    local loaded = rt(song)
    assert.is_nil(tab.get_note(loaded, 1, 1, 1, 1))
    assert.equals(4,  tab.get_note(loaded, 1, 1, 1, 2))
    assert.equals(3,  tab.get_note(loaded, 1, 1, 1, 3))
  end)

  it("metadata (title, subtitle, tuning, order) survives round-trip", function()
    local song = tab.new({ title = "My Song", subtitle = "By Me", tuning = "Drop D", order = "A B A" })
    local loaded = rt(song)
    assert.equals("My Song", loaded.title)
    assert.equals("By Me",   loaded.subtitle)
    assert.equals("Drop D",  loaded.tuning)
    assert.equals("A B A",   loaded.order)
  end)

  it("section name survives round-trip", function()
    local song = tab.new()
    tab.set_section_name(song, 1, "Chorus")
    local loaded = rt(song)
    assert.equals("Chorus", loaded.sections[1].name)
  end)

  it("repeat markers survive round-trip", function()
    local song = tab.new()
    tab.toggle_repeat_start(song, 1)
    tab.toggle_repeat_end(song, 1)
    local loaded = rt(song)
    assert.is_true(loaded.sections[1].repeat_start)
    assert.is_true(loaded.sections[1].repeat_end)
  end)

  it("multiple sections survive round-trip", function()
    local song = tab.new()
    tab.add_section(song)
    tab.set_section_name(song, 1, "Intro")
    tab.set_section_name(song, 2, "Verse")
    local loaded = rt(song)
    assert.equals(2,       #loaded.sections)
    assert.equals("Intro", loaded.sections[1].name)
    assert.equals("Verse", loaded.sections[2].name)
  end)

  it("render after round-trip shows correct notes on non-e strings", function()
    local render = require("fret.render")
    local config = require("fret.config")
    config.setup({})
    local song = tab.new({ time_sig = { num = 4, den = 4 }, subdivision = 1 })
    tab.set_note(song, 1, 1, 1, 2, 4)
    tab.set_note(song, 1, 1, 1, 3, 3)
    local loaded = rt(song)
    local lines  = render.render(loaded)
    assert.falsy(lines[4]:match("[0-9]"))
    assert.truthy(lines[5]:match("4"))
    assert.truthy(lines[6]:match("3"))
  end)
end)
